version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackathon_bi_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.5
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"

volumes:
  postgres_data: 
  redis:
